// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using robot_generator.Data;

#nullable disable

namespace robot_generator.Migrations
{
    [DbContext(typeof(RobotDbContext))]
    partial class RobotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("robot_generator.Models.Robot", b =>
                {
                    b.Property<string>("RobotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RobotPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RobotId");

                    b.ToTable("Robots");
                });
#pragma warning restore 612, 618
        }
    }
}
